title: Jarfil.GitHub.io
description: 
google_analytics: 
show_downloads: false
theme: jekyll-theme-leap-day

gems:
  - jekyll-mentions

collections:
  posts:
    permalink: "/blog/:year/:month/:day/:title/"
    output: true
defaults:
- scope:
    path: _posts
    type: posts
